apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: travelbooking-dev-applicationset
  namespace: argocd

spec:
  generators:
    # 🔥 MATRIX = envs × projects x services
    - matrix:
        generators:

          # 🔹 ENVIRONMENTS
          - list:
              elements:
                - env: dev
                # - env: stage
                # - env: prod

          # 🔹 PROJECTS
          - list:
              elements:
                - project: travelbooking
                  repoURL: https://github.com/vaheedgit26/vg-travelbooking.git
                # 👉 future ready
                # - project: paymentplatform
                #   repoURL: https://github.com/org/paymentplatform.git

          # 🔹 SERVICES (auto-discovered from ONE env only to avoid duplication)
          - git:
              repoURL: https://github.com/vaheedgit26/vg-travelbooking.git
              revision: main
              directories:
                - path: gitops/dev/helm/*			
  # Application template
  template:
    metadata:
      name: "{{project}}-{{env}}-{{path.basename}}"
      namespace: argocd

      labels:
        project: "{{project}}"
        env: "{{env}}"
        component: "{{path.basename}}"
        app.kubernetes.io/part-of: "{{project}}"

      annotations:
        # 🔹 Sync order
        argocd.argoproj.io/sync-wave: >
          {{- if eq .path.basename "database" -}}0
          {{- else if or (eq .path.basename "user") (eq .path.basename "search") (eq .path.basename "booking") (eq .path.basename "payment") (eq .path.basename "notification") -}}1
          {{- else if eq .path.basename "frontend" -}}2
          {{- else -}}3
          {{- end }}

    spec:
      project: "{{project}}-{{env}}"              # This name should match with the name of 'AppProject' created previously

      source:
        repoURL: "{{repoURL}}"
        targetRevision: main

        # 🔥 dynamic env + service
        path: "gitops/{{env}}/helm/{{path.basename}}"

        helm:
          releaseName: "{{project}}-{{env}}-{{path.basename}}"
          valueFiles:
            - values.yaml
            # optional per-env override
            # - "../../values-{{env}}.yaml"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{project}}-{{env}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
