# ──────────────────────────────────────
# Frontend
# ──────────────────────────────────────
namespace: travelbooking

image:
    uri: 254405569649.dkr.ecr.us-east-1.amazonaws.com
    name: travelbooking/frontend
    version: v1

deployment:
    name: frontend-deploy
    replicas: 1

service:
    name: frontend-svc
    port: 80
    targetPort: 80

hpa:
    name: frontend-hpa
    minReplicas: 1
    maxReplicas: 3

# ──────────────────────────────────────
# Postgre DB
# ──────────────────────────────────────
postgre:
  host: shopverse-dev-mysql.ca9aykaigakf.us-east-1.rds.amazonaws.com
  port: 5432
  externalNameService: travelbooking-postgre
  database: bookingdb
  user: shopverse
  sslmode: disable
    
jwtSecret: ""

# ──────────────────────────────────────
# Ingress
# ──────────────────────────────────────
 ingress:
    enabled: false
    name: travelbooking-booking-ingress
    ingressClassName: alb
    path: /api
    pathType: Prefix
    host: ""

    annotations:
      # Backend-specific health check
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    
      # This is important to mix all the service ingresses and form one complete ingress
      alb.ingress.kubernetes.io/group.name: shopverse-dev    # This should be same in all the ingress.yaml files to collaboratively create single ALB

      alb.ingress.kubernetes.io/group.order: "1"   # 🔥 higher priority
      
