frontend:
  image:
    uri: 254405569649.dkr.ecr.us-east-1.amazonaws.com
    name: shopverse-frontend
    version: v1

  deployment:
    name: shopverse-frontend
    replicas: 1

  service:
    name: shopverse-frontend-svc
    port: 8080
  
  ingress:
    enabled: false
    name: shopverse-frontend-ingress
    ingressClassName: alb
    path: /
    pathType: Prefix
    host: ""

    annotations:
      # Backend-specific health check
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    
      # This is important to mix all the service ingresses and form one complete ingress
      alb.ingress.kubernetes.io/group.name: shopverse-dev    # This should be same in all the ingress.yaml files to collaboratively create single ALB

      alb.ingress.kubernetes.io/group.order: "2"   # 🔥 lower priority

# ──────────────────────────────────────
# MySQL
# ──────────────────────────────────────
mysql:
  host: shopverse-dev-mysql.ca9aykaigakf.us-east-1.rds.amazonaws.com
  externalNameService: shopverse-mysql
  database: shopverse
  user: shopverse
    

jwtSecret: ""
