apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: production
  PORT: "3002"
  DB_HOST: {{ .Values.postgre.externalNameService | quote }}
  DB_PORT: {{ .Values.postgre.port | quote }}
  DB_NAME: {{ .Values.postgre.database | quote }}
  # DB_SSLMODE: {{ .Values.db.sslmode | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
