apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.paymentService.servicename }}
  namespace: {{ .Values.namespace }}
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - name: http
    port: 3004
    targetPort: 3004
