# ──────────────────────────────────────
# Payment
# ──────────────────────────────────────
namespace: travelbooking-dev

image:
    uri: 254405569649.dkr.ecr.us-east-1.amazonaws.com
    name: travelbooking/payment
    version: v1

deployment:
    name: payment-deploy
    replicas: 1

service:
    name: payment-svc
    port: 3004
    targetPort: 3004

hpa:
    name: payment-hpa
    minReplicas: 1
    maxReplicas: 3

configmap:
    name: payment-config

secret:
    name: travelbooking-dev-postgre-jwt-credentials

bookingService:
    servicename: booking-svc

notificationService:
    servicename: notification-svc

# ──────────────────────────────────────
# Postgre DB
# ──────────────────────────────────────
postgre:
  host: shopverse-dev-mysql.ca9aykaigakf.us-east-1.rds.amazonaws.com
  port: 5432
  externalNameService: travelbooking-postgre-ens
  database: paymentdb
  user: postgre
  sslmode: disable
    
jwtSecret: ""
