apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.searchService.servicename }}
  namespace: {{ .Values.namespace }}
  labels:
    app: search-service
spec:
  type: ClusterIP
  selector:
    app: search-service
  ports:
  - name: http
    port: 3002
    targetPort: 3002
