apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }} # travelbooking-booking-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: production
  PORT: {{ .Values.service.targetPort | quote }} # "3003"
  DB_HOST: {{ .Values.postgre.externalNameService | quote }}
  DB_PORT: {{ .Values.postgre.port | quote }}
  DB_NAME: {{ .Values.postgre.database | quote }}
  DB_SSLMODE: require  # disable
  USER_SERVICE_URL: "http://{{ .Values.userService.servicename }}:3001"
  NOTIFICATION_SERVICE_URL: "http://{{ .Values.notificationService.servicename }}:3005"
