apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: booking-service
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
  - name: http
    port: {{ .Values.service.port }}             # 3003
    targetPort: {{ .Values.service.targetPort }} # 3003
