apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}                         # shopverse-config
  labels:
    app: shopverse
data:
  DB_HOST: {{ .Values.mysql.externalNameService | quote }}   # "shopverse-mysql"
  DB_PORT: {{ .Values.mysql.port | quote }}                  # "3306"
  DB_NAME: {{ .Values.mysql.database | quote }}              # "shopverse"
  FRONTEND_ORIGIN: "*"                                       # "http://shopverse-frontend-svc:80"
