apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deployment.name }}
  labels:
    app: shopverse
    component: backend
spec:
  replicas: {{ .Values.backend.deployment.replicas }}
  selector:
    matchLabels:
      app: shopverse
      component: backend
  template:
    metadata:
      labels:
        app: shopverse
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ include "shopverse.backend.image" . }}"
          imagePullPolicy: Always        # IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.configmap.name }}  # shopverse-config
            - secretRef:
                name: {{ .Values.backend.secret.name }}     # shopverse-dev-mysql-jwt-credentials
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu | quote }}        # "100m"
              memory: {{ .Values.backend.resources.requests.memory | quote }}  # "128Mi"
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu | quote }}          # "200m"
              memory: {{ .Values.backend.resources.limits.memory | quote }}    # "256Mi"   
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
