{{- if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backend.ingress.name }}                             # shopverse-backend-ingress
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.backend.ingress.ingressClassName }}     # alb
  rules:
    - http:
        paths:
          - path: {{ .Values.backend.ingress.path }}                   # /api
            pathType: {{ .Values.backend.ingress.pathType }}           # Prefix
            backend:
              service:
                name: {{ .Values.backend.service.name }}
                port:
                  number: {{ .Values.backend.service.port }}           # 8080
{{- end }}
