apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  labels:
    app: shopverse
    component: backend
spec:
  #type: NodePort
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }} # 8080
      protocol: TCP
      # nodePort: 30081
  selector:
    app: shopverse
    component: backend
