{{- if .Values.baseIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.baseIngress.name }}                            # shopverse-base-ingress
  {{- with .Values.baseIngress.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.baseIngress.ingressClassName }}    # alb

  # ⚠️ Rule (required to create ALB)
  rules:
    - http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 8080 
{{- end }}
