# ──────────────────────────────────────
# User
# ──────────────────────────────────────
namespace: travelbooking-dev

image:
    uri: 254405569649.dkr.ecr.us-east-1.amazonaws.com
    name: travelbooking/user
    version: v1

deployment:
    name: user-deploy
    replicas: 1

service:
    name: user-svc
    port: 3001
    targetPort: 3001

hpa:
    name: user-hpa
    minReplicas: 1
    maxReplicas: 3

configmap:
    name: user-config

secret:
    name: travelbooking-dev-postgre-jwt-credentials

# ──────────────────────────────────────
# Postgre DB
# ──────────────────────────────────────
postgre:
  host: shopverse-dev-mysql.ca9aykaigakf.us-east-1.rds.amazonaws.com
  port: 5432
  externalNameService: travelbooking-postgre-ens
  database: userdb
  user: postgre
  sslmode: disable
    
jwtSecret: ""

# ──────────────────────────────────────
# Ingress
# ──────────────────────────────────────
 ingress:
    enabled: false
    name: travelbooking-booking-ingress
    ingressClassName: alb
    path: /api
    pathType: Prefix
    host: ""

    annotations:
      # Backend-specific health check
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    
      # This is important to mix all the service ingresses and form one complete ingress
      alb.ingress.kubernetes.io/group.name: shopverse-dev    # This should be same in all the ingress.yaml files to collaboratively create single ALB

      alb.ingress.kubernetes.io/group.order: "1"   # 🔥 higher priority
      
