# ──────────────────────────────────────
# User
# ──────────────────────────────────────
namespace: travelbooking-dev

image:
    uri: 254405569649.dkr.ecr.us-east-1.amazonaws.com
    name: travelbooking/user
    version: v2

deployment:
    name: user-deploy
    replicas: 1

service:
    name: user-svc
    port: 3001
    targetPort: 3001

hpa:
    name: user-hpa
    minReplicas: 1
    maxReplicas: 3

configmap:
    name: user-config

secret:
    name: travelbooking-dev-postgre-jwt-creds

# ──────────────────────────────────────
# Postgre DB
# ──────────────────────────────────────
postgre:
  host: shopverse-dev-mysql.ca9aykaigakf.us-east-1.rds.amazonaws.com
  port: 5432
  externalNameService: travelbooking-postgre-ens
  database: userdb
  user: postgre
  sslmode: disable
    
jwtSecret: ""
