apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
  - name: http
    port: {{ .Values.service.port }} # 3005
    targetPort: {{ .Values.service.targetPort }} # 3005
