apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: travel-booking-gateway
  namespace: travel-booking
  annotations:
    kubernetes.io/ingress.global-static-ip-name: travel-booking-ip
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  # HTTP listener — accepts traffic only for your domain
  - name: http
    port: 80
    protocol: HTTP
    hostname: vijaygiduthuri.in
    allowedRoutes:
      namespaces:
        from: All
