apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: production
  PORT: "3002"
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.searchDb | quote }}
  DB_SSLMODE: {{ .Values.db.sslmode | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
