apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
