apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: travelbooking-dev-postgre-jwt-creds
  # namespace: dev
  labels:
    env: dev
    managed-by: terraform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-css                     # ClusterSecretStore or SecretStore k8s object name
    kind: ClusterSecretStore
  target:
    name: travelbooking-dev-postgre-jwt-creds         # K8s Secret name
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: /travelbooking/dev/postgre-jwt-creds     # AWS Secret name
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /travelbooking/dev/postgre-jwt-creds
        property: password    
    - secretKey: JWT_SECRET
      remoteRef:
        key: /travelbooking/dev/postgre-jwt-creds
        property: jwt_secret
