apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shopverse-dev-mysql-jwt-credentials
  # namespace: dev
  labels:
    env: dev
    managed-by: terraform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager                        # ClusterSecretStore or SecretStore k8s object name
    kind: ClusterSecretStore
  target:
    name: shopverse-dev-mysql-jwt-credentials        # K8s Secret name
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: /shopverse/dev/mysql-jwt-credentials     # AWS Secret name
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /shopverse/dev/mysql-jwt-credentials
        property: password    
    - secretKey: JWT_SECRET
      remoteRef:
        key: /shopverse/dev/mysql-jwt-credentials
        property: jwt_secret
