apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bookingService.servicename }}
  namespace: {{ .Values.namespace }}
  labels:
    app: booking-service
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
  - name: http
    port: 3003
    targetPort: 3003
