# ──────────────────────────────────────
# Booking
# ──────────────────────────────────────
namespace: travelbooking-dev

image:
    uri: 254405569649.dkr.ecr.us-east-1.amazonaws.com
    name: travelbooking/booking
    version: v1

deployment:
    name: booking-deploy
    replicas: 1

service:
    name: booking-svc
    port: 3003
    targetPort: 3003

hpa:
    name: booking-hpa
    minReplicas: 1
    maxReplicas: 3

configmap:
    name: booking-config

secret:
    name: travelbooking-dev-postgre-jwt-creds

userService:
    servicename: user-svc

notificationService:
    servicename: notification-svc
    
# ──────────────────────────────────────
# Postgre DB
# ──────────────────────────────────────
postgre:
  host: shopverse-dev-mysql.ca9aykaigakf.us-east-1.rds.amazonaws.com
  port: 5432
  externalNameService: travelbooking-postgre-ens
  database: bookingdb
  user: postgres
  sslmode: disable
    
jwtSecret: ""
