apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-service-monitor
  namespace: travel-booking
  labels:
    app: payment-service
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: payment-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - travel-booking
